#!/usr/bin/env node
// Phase 0 inventory. READ-ONLY. Never opens files matched by data/secret-paths.json;
// for those it reports names only. Output: JSON on stdout.
//
// Usage: node detect.mjs [--root <repo>]
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {
  parseArgs, repoRoot, git, run, toPosix, loadSecretSpec, isSecretPath, matchesAny, canonicalPath,
  readJsonFile, skillVersion, IS_WINDOWS, ok, fail,
} from './lib.mjs';
import { parseToml } from './toml.mjs';

const args = parseArgs(process.argv.slice(2));
const root = args.root ? path.resolve(args.root) : repoRoot();
if (!root) fail('not inside a git repository; run from the project root');

const spec = loadSecretSpec();
const SOURCE_EXT = /\.(ts|tsx|js|mjs|cjs|py|go|java|kt|rb|php|cs|rs|scala|ex|exs)$/i;
const V1_PROVENANCE = /Generated by project-setup(?!\s+v2)/;
const V2_MARKER = /<!--\s*project-setup:begin\b/;

function lsFiles(extra = []) {
  const r = git(['ls-files', '-z', ...extra], root);
  if (r.status !== 0) return [];
  return r.stdout.split('\0').filter(Boolean).map((p) => p.replace(/\\/g, '/'));
}

const tracked = lsFiles();
const untracked = lsFiles(['--others', '--exclude-standard']);
const ignored = lsFiles(['--others', '--ignored', '--exclude-standard']);
const visible = [...new Set([...tracked, ...untracked])];

const exists = (rel) => fs.existsSync(path.join(root, rel));
const safeRead = (rel) => {
  if (isSecretPath(rel, spec)) return null; // never read secret-matched files
  try { return fs.readFileSync(path.join(root, rel), 'utf8'); } catch { return null; }
};

// Strip fenced and inline code so an `@AGENTS.md` inside backticks is not counted as an import.
function importsAgentsMd(text) {
  if (!text) return false;
  const stripped = text.replace(/```[\s\S]*?```/g, '').replace(/`[^`]*`/g, '');
  return /(^|\s)@(\.\/)?AGENTS\.md(\s|$)/m.test(stripped);
}

// ---- instruction files ----------------------------------------------------
const INSTRUCTION_NAMES = /(^|\/)(AGENTS\.md|AGENTS\.override\.md|CLAUDE\.md|CLAUDE\.local\.md|\.claude\/CLAUDE\.md)$/;
const instructionFiles = [...new Set([...visible, ...ignored])]
  .filter((p) => INSTRUCTION_NAMES.test(p))
  .filter((p) => !p.includes('node_modules/'))
  .map((p) => {
    const text = safeRead(p);
    return {
      path: p,
      tracked: tracked.includes(p),
      lines: text ? text.split(/\r?\n/).length : null,
      bytes: text ? Buffer.byteLength(text) : null,
      importsAgentsMd: /CLAUDE\.md$/.test(p) ? importsAgentsMd(text) : undefined,
      v1Provenance: text ? V1_PROVENANCE.test(text) : false,
      v2Blocks: text ? V2_MARKER.test(text) : false,
      crlf: text ? /\r\n/.test(text) : null,
    };
  });

// ---- tool config inventory -------------------------------------------------
const listDir = (rel) => { try { return fs.readdirSync(path.join(root, rel)); } catch { return []; } };
const claude = {
  settingsJson: exists('.claude/settings.json'),
  settingsLocalJson: exists('.claude/settings.local.json'),
  agents: listDir('.claude/agents'),
  skills: listDir('.claude/skills'),
  rulesDir: exists('.claude/rules'),
  claudeignore: exists('.claudeignore'),
};
const codex = {
  projectConfigToml: exists('.codex/config.toml'),
  agents: listDir('.codex/agents'),
  repoSkills: listDir('.agents/skills'),
};

// ---- .ai state ---------------------------------------------------------------
let manifest = null;
if (exists('.ai/manifest.json')) {
  try { manifest = readJsonFile(path.join(root, '.ai/manifest.json')); } catch (e) { manifest = { parseError: e.message }; }
}
const lockHeld = exists('.ai/.setup.lock');
const runs = listDir('.ai/.run');
const v1Docs = ['.ai/context', '.ai/decisions'].filter(exists);
const v1ProvenanceInAi = visible
  .filter((p) => p.startsWith('.ai/') && p.endsWith('.md'))
  .some((p) => V1_PROVENANCE.test(safeRead(p) || ''));

// ---- secrets: NAMES ONLY -----------------------------------------------------
const ENV_TEMPLATE = /(^|\/)\.env\.(example|sample|template)$/;
const trackedSecretPaths = tracked.filter((p) => isSecretPath(p, spec) && !ENV_TEMPLATE.test(p));
const envTemplates = visible.filter((p) => ENV_TEMPLATE.test(p));
const presentSecretPaths = [...new Set([...untracked, ...ignored])].filter((p) => isSecretPath(p, spec) && !p.startsWith('.ai/.run/'));
const contentRiskFiles = visible.filter((p) => matchesAny(p, spec.contentRisk.globs));

// ---- project facts (non-secret) ---------------------------------------------
const lockfiles = ['package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', 'bun.lockb', 'bun.lock'].filter(exists);
let pkg = null;
if (exists('package.json')) {
  try {
    const p = readJsonFile(path.join(root, 'package.json'));
    pkg = { name: p.name, scripts: Object.keys(p.scripts || {}), engines: p.engines || null, hasTypescript: Boolean((p.devDependencies || {}).typescript || (p.dependencies || {}).typescript) };
  } catch (e) { pkg = { parseError: e.message }; }
}
const sourceFileCount = tracked.filter((p) => SOURCE_EXT.test(p) && !p.includes('node_modules/')).length;

// ---- git state ---------------------------------------------------------------
const branch = git(['rev-parse', '--abbrev-ref', 'HEAD'], root).stdout || null;
const head = git(['rev-parse', '--short', 'HEAD'], root).stdout || null;
const porcelain = git(['status', '--porcelain=v1', '-z'], root).stdout.split('\0').filter(Boolean).map((l) => l.slice(3));
const gitDir = git(['rev-parse', '--git-dir'], root).stdout;
const isLinkedWorktree = /\/worktrees\//.test(toPosix(gitDir || ''));

// ---- tool versions (fixed command strings only) -----------------------------
function version(cmd) {
  // On Windows the CLI is often only reachable through a .cmd/.exe shim (PowerShell may prefer a blocked .ps1).
  const names = IS_WINDOWS ? [cmd, `${cmd}.cmd`, `${cmd}.exe`] : [cmd];
  for (const name of names) {
    const r = IS_WINDOWS ? run(`${name} --version`, [], { shell: true }) : run(name, ['--version']);
    if (r.status === 0 && r.stdout) return r.stdout.split('\n')[0];
  }
  return null;
}
const tools = {
  claude: version('claude'), codex: version('codex'), gitleaks: version('gitleaks'), node: process.version,
  runningInsideClaudeCode: Boolean(process.env.CLAUDECODE),
};

// ---- user-level settings: extract only the keys we need, never print the rest -
const home = os.homedir();
// Honour the tools' own config-dir overrides so isolated sessions are reported correctly.
const claudeHome = process.env.CLAUDE_CONFIG_DIR ? path.resolve(process.env.CLAUDE_CONFIG_DIR) : path.join(home, '.claude');
const codexHome = process.env.CODEX_HOME ? path.resolve(process.env.CODEX_HOME) : path.join(home, '.codex');
function claudeInstructionFilesMode() {
  try {
    const s = readJsonFile(path.join(claudeHome, 'settings.json'));
    const pc = s.pluginConfigs || {};
    const entry = pc['cc-plugin-agents-md@builtin'] || pc['agents-md@builtin'];
    return entry?.options?.instructionFiles || 'default(claude-md-or-agents-md)';
  } catch { return 'unknown'; }
}
function codexUserConfigFlags() {
  const p = path.join(codexHome, 'config.toml');
  let text;
  try { text = fs.readFileSync(p, 'utf8'); } catch { return { present: false }; }
  const line = (key) => (text.match(new RegExp(`^\\s*${key}\\s*=\\s*"?([^"\\n]+)"?`, 'm')) || [])[1] || null;
  return {
    present: true,
    sandbox_mode: line('sandbox_mode'),
    default_permissions: line('default_permissions'),
    hasSandboxWorkspaceWriteTable: /^\s*\[sandbox_workspace_write\]/m.test(text),
    mixesLegacyAndProfiles: Boolean(line('sandbox_mode') && line('default_permissions')),
  };
}

// ---- installed skill copies ----------------------------------------------------
/** Directories named project-setup containing SKILL.md under base (bounded depth, links not followed). */
function scanSkillCopies(base, maxDepth) {
  const found = [];
  const stack = [{ dir: base, depth: 0 }];
  while (stack.length) {
    const { dir, depth } = stack.pop();
    let entries = [];
    try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { continue; }
    for (const e of entries) {
      const full = path.join(dir, e.name);
      const linked = e.isSymbolicLink();
      let isDir = e.isDirectory();
      if (linked) { try { isDir = fs.statSync(full).isDirectory(); } catch { isDir = false; } } // dangling link = absent
      if (!isDir) continue;
      // A linked skill folder is a real installation (tools follow it); read-only discovery must report it.
      if (e.name === 'project-setup' && fs.existsSync(path.join(full, 'SKILL.md'))) found.push(full);
      else if (!linked && depth < maxDepth) stack.push({ dir: full, depth: depth + 1 }); // no recursion through links: no cycles
    }
  }
  return found;
}

function readJsonQuiet(p) { try { return readJsonFile(p); } catch { return null; } }

/** skillOverrides set to "off" in any Claude settings layer this session would load. */
/** The documented skillOverrides states. Anything else is invalid and must not change the effective value. */
const OVERRIDE_STATES = new Set(['on', 'off', 'name-only', 'user-invocable-only']);
const invalidOverrides = [];

/**
 * Keys whose EFFECTIVE skillOverrides value is "off". Values are merged per key in Claude Code's precedence order for
 * the layers read here (lowest first): user settings -> shared project settings -> project-local settings. A later
 * layer replaces an earlier value for the same key only with a documented value (on, off, name-only,
 * user-invocable-only, exact spelling). Invalid values (null, booleans, numbers, objects, other strings, other case or
 * whitespace) are skipped, so the lower valid value stays in effect, and they are reported in invalidOverrides.
 * Managed policy and command-line settings are not visible to this script and are not inferred.
 */
function claudeOffOverrides() {
  const effective = new Map();
  const layers = [['user', path.join(claudeHome, 'settings.json')], ['shared project', path.join(root, '.claude', 'settings.json')], ['project-local', path.join(root, '.claude', 'settings.local.json')]];
  for (const [layer, p] of layers) {
    const o = readJsonQuiet(p)?.skillOverrides;
    if (!o || typeof o !== 'object' || Array.isArray(o)) continue;
    for (const [k, v] of Object.entries(o)) {
      if (typeof v === 'string' && OVERRIDE_STATES.has(v)) effective.set(k, v);
      else invalidOverrides.push({ layer, key: k, value: v === null ? null : typeof v === 'string' ? v : typeof v });
    }
  }
  return new Set([...effective].filter(([, v]) => v === 'off').map(([k]) => k));
}

/** SKILL.md paths disabled through [[skills.config]] enabled=false in Codex config files. */
function codexDisabledSkills() {
  const byFile = {};
  let files = [];
  try { files = fs.readdirSync(codexHome).filter((f) => f === 'config.toml' || f.endsWith('.config.toml')); } catch { /* none */ }
  for (const f of files) {
    let text; try { text = fs.readFileSync(path.join(codexHome, f), 'utf8'); } catch { continue; }
    const { data } = parseToml(text);
    const list = Array.isArray(data?.skills?.config) ? data.skills.config : [];
    byFile[f] = list.filter((x) => x && x.enabled === false && typeof x.path === 'string').map((x) => canonicalPath(path.dirname(x.path)));
  }
  return byFile;
}

function findSkillInstalls() {
  // Each location belongs to exactly one tool. A conflict is two ACTIVE copies visible to the SAME tool;
  // one repo-level copy per tool (.claude/skills + .agents/skills) is the intended layout.
  // Nested folders are scanned because both tools load synced skills from subfolders (e.g. skills/synced/<id>/).
  const candidates = [
    ...scanSkillCopies(path.join(claudeHome, 'skills'), 4).map((dir) => ({ tool: 'claude', scope: /[\\/]synced[\\/]/.test(dir) ? 'synced' : 'user', dir })),
    ...scanSkillCopies(path.join(root, '.claude', 'skills'), 0).map((dir) => ({ tool: 'claude', scope: 'repo', dir })),
    ...scanSkillCopies(path.join(home, '.agents', 'skills'), 4).map((dir) => ({ tool: 'codex', scope: /[\\/]synced[\\/]/.test(dir) ? 'synced' : 'user', dir })),
    ...scanSkillCopies(path.join(codexHome, 'skills'), 4).map((dir) => ({ tool: 'codex', scope: 'user-legacy', dir })),
    ...scanSkillCopies(path.join(root, '.agents', 'skills'), 0).map((dir) => ({ tool: 'codex', scope: 'repo', dir })),
    ...scanSkillCopies(path.join(claudeHome, 'plugins'), 6).map((dir) => ({ tool: 'claude', scope: 'plugin', dir })),
  ];
  const off = claudeOffOverrides();
  const codexOff = codexDisabledSkills();
  const found = [];
  const seen = new Set();
  for (const c of candidates) {
    const canon = canonicalPath(c.dir);
    const key = `${c.tool}|${canon}`;
    if (seen.has(key)) continue; // same directory reached twice (e.g. CODEX_HOME == ~/.agents) is one copy
    seen.add(key);
    let ver = 'unknown';
    try { ver = fs.readFileSync(path.join(c.dir, 'VERSION'), 'utf8').trim(); } catch { ver = c.scope === 'plugin' ? 'plugin' : 'v1-or-unversioned'; }
    const disabledBy = [];
    let overrideNote = null;
    if (c.tool === 'claude') {
      // Runtime identities: user/repo skill = "project-setup"; skill synced from claude.ai = "anthropic-skills:project-setup".
      // Plugin skills are excluded from skillOverrides (Claude Code docs), so an override never disables them here.
      const identity = c.scope === 'synced' ? 'anthropic-skills:project-setup' : c.scope === 'plugin' ? null : 'project-setup';
      if (identity && off.has(identity)) disabledBy.push(`skillOverrides "${identity}": "off"`);
      if (c.scope === 'plugin' && [...off].some((k) => /:project-setup$/.test(k))) overrideNote = 'skillOverrides does not apply to plugin skills; disable the plugin or have its owner remove v1';
    } else {
      if ((codexOff['config.toml'] || []).includes(canon)) disabledBy.push('config.toml [[skills.config]] enabled=false');
    }
    const profiles = c.tool === 'codex' ? Object.entries(codexOff).filter(([f, l]) => f !== 'config.toml' && l.includes(canon)).map(([f]) => f.replace(/\.config\.toml$/, '')) : [];
    found.push({ tool: c.tool, scope: c.scope, path: toPosix(c.dir), version: ver, disabled: disabledBy.length > 0, disabledBy, disabledOnlyInProfiles: profiles, ...(overrideNote ? { note: overrideNote } : {}) });
  }
  return found;
}

// ---- mode classification (evidence-based) --------------------------------------
const evidence = [];
const rootClaude = instructionFiles.find((f) => f.path === 'CLAUDE.md' || f.path === '.claude/CLAUDE.md');
const rootAgents = instructionFiles.find((f) => f.path === 'AGENTS.md');
let mode;
if (manifest && manifest.schema === 2) {
  mode = 'update'; evidence.push('.ai/manifest.json schema 2');
} else if (rootClaude?.v1Provenance || v1ProvenanceInAi) {
  mode = 'migrate-v1'; evidence.push('v1 provenance comment found ("Generated by project-setup")');
} else if (rootClaude && rootAgents) {
  mode = 'adopt'; evidence.push('both CLAUDE.md and AGENTS.md exist without v2 manifest; compare semantically before any change');
} else if (rootClaude || v1Docs.length || claude.agents.length) {
  mode = 'adopt'; evidence.push('existing Claude configuration without reliable v1 provenance');
} else if (rootAgents) {
  mode = 'add-claude'; evidence.push('AGENTS.md exists, no CLAUDE.md');
} else {
  mode = sourceFileCount === 0 ? 'empty-repo' : 'fresh';
  evidence.push(sourceFileCount === 0 ? 'no tracked source files' : 'no AI configuration found');
}
if (v1Docs.length && mode !== 'migrate-v1' && mode !== 'update') evidence.push(`.ai/ exists (${v1Docs.join(', ')}) but is NOT treated as v1 proof`);

const warnings = [];
if (claude.claudeignore) warnings.push('.claudeignore exists but Claude Code ignores it; its entries must become Read deny rules');
if (trackedSecretPaths.length) warnings.push('secret-pattern files (not env templates) are TRACKED in git; stop and escalate before generating docs');
if (envTemplates.length) warnings.push('env templates present; inspect them only via env-keys.mjs (names + value classification, never values)');
if (lockHeld) warnings.push('.ai/.setup.lock exists; another run may be in progress or crashed (see lock.mjs status)');
if (porcelain.length) warnings.push('working tree has uncommitted changes; only files touched by the plan must be clean');
const cuf = codexUserConfigFlags();
if (cuf.mixesLegacyAndProfiles) warnings.push('~/.codex/config.toml sets both sandbox_mode and default_permissions: legacy sandbox settings take precedence and the deny-read profile is NOT active');
const installs = findSkillInstalls();
const installConflicts = {};
for (const tool of ['claude', 'codex']) {
  const mine = installs.filter((i) => i.tool === tool && !i.disabled);
  if (mine.length > 1) installConflicts[tool] = mine.map((i) => `${i.scope}: ${i.path} (${i.version})`);
}
for (const inv of invalidOverrides) {
  warnings.push(`skillOverrides "${inv.key}" in ${inv.layer} settings has an invalid value (${JSON.stringify(inv.value)}); ignored, the lower layer's value stays in effect`);
}
for (const i of installs.filter((x) => x.scope === 'repo' && x.disabled)) {
  warnings.push(`${i.tool}: the repo copy of project-setup is disabled (${i.disabledBy.join('; ')}); this version will not run`);
}
for (const [tool, list] of Object.entries(installConflicts)) {
  warnings.push(`${tool}: ${list.length} project-setup copies are visible to the same tool (${list.join('; ')}); keep exactly one`);
}

ok({
  skillVersion: skillVersion(),
  root: toPosix(root),
  platform: { os: process.platform, release: os.release(), wsl: Boolean(process.env.WSL_DISTRO_NAME) },
  tools,
  git: { branch, head, isLinkedWorktree, dirtyPaths: porcelain },
  mode, evidence, warnings,
  instructionFiles,
  claude: { ...claude, userInstructionFilesMode: claudeInstructionFilesMode() },
  codex: { ...codex, userConfig: cuf },
  ai: { manifest: manifest ? { schema: manifest.schema, skillVersion: manifest.skillVersion, mode: manifest.mode } : null, lockHeld, runs, v1Docs },
  project: { package: pkg, lockfiles, sourceFileCount, docsDir: exists('docs'), readme: exists('README.md'), todo: exists('TODO.md') },
  secrets: { trackedSecretPaths, envTemplates, presentSecretPaths, contentRiskFiles },
  installs,
  installConflicts,
  invalidOverrides,
  installsNote: 'Filesystem scan (incl. synced subfolders) plus Claude skillOverrides "off" and Codex config.toml [[skills.config]] enabled=false. Copies disabled only in a Codex profile are reported but still counted, because the profile applies only when Codex is started with -p. Skills synced from claude.ai can appear only after the first restart. The skill list reported by a NEW session of the running tool is authoritative.',
});
